"""Add prefix column to server config table

Revision ID: 16735f2348ae
Revises: 13b306d3769a
Create Date: 2020-04-20 21:17:08.233658

"""

# revision identifiers, used by Alembic.
revision = '16735f2348ae'
down_revision = '13b306d3769a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_config', sa.Column('prefix', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_config', 'prefix')
    # ### end Alembic commands ###
