"""Create self_assign_roles table

Revision ID: 67c73a3d2ea6
Revises: 9425e69f4a16
Create Date: 2020-07-13 21:08:10.678805

"""

# revision identifiers, used by Alembic.
revision = '67c73a3d2ea6'
down_revision = '9425e69f4a16'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_assign_roles',
    sa.Column('guild', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['guild'], ['server_config.server'], ),
    sa.PrimaryKeyConstraint('guild', 'role_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_assign_roles')
    # ### end Alembic commands ###
