"""Add star_threshold to table server_config

Revision ID: 7baf663f0bb2
Revises: b58e52154ab0
Create Date: 2019-03-16 20:10:54.943038

"""

# revision identifiers, used by Alembic.
revision = '7baf663f0bb2'
down_revision = 'b58e52154ab0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_config', sa.Column('star_threshold', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_config', 'star_threshold')
    # ### end Alembic commands ###
