"""create custom role chart table

Revision ID: 85ffec7736c0
Revises: 7baf663f0bb2
Create Date: 2019-09-28 20:55:36.711830

"""

# revision identifiers, used by Alembic.
revision = '85ffec7736c0'
down_revision = '7baf663f0bb2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_role_chart',
    sa.Column('server', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['server'], ['server_config.server'], ),
    sa.PrimaryKeyConstraint('role'),
    sa.UniqueConstraint('role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_config', 'custom_role_chart')
    op.drop_table('server_role_chart')
    # ### end Alembic commands ###
