"""Add mod role column to server config

Revision ID: 8f61243b2601
Revises: 5f1cf30db9e0
Create Date: 2020-04-24 20:38:45.598400

"""

# revision identifiers, used by Alembic.
revision = '8f61243b2601'
down_revision = '5f1cf30db9e0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_config', sa.Column('mod_role', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_config', 'mod_role')
    # ### end Alembic commands ###
