"""Add log channel column to server config

Revision ID: 9425e69f4a16
Revises: 8f61243b2601
Create Date: 2020-04-24 20:48:10.296408

"""

# revision identifiers, used by Alembic.
revision = '9425e69f4a16'
down_revision = '8f61243b2601'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_config', sa.Column('log_channel', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_config', 'log_channel')
    # ### end Alembic commands ###
