"""added tables server_config, stars

Revision ID: b58e52154ab0
Revises: 221ba75a0b4
Create Date: 2019-03-15 23:04:15.897852

"""

# revision identifiers, used by Alembic.
revision = 'b58e52154ab0'
down_revision = '221ba75a0b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_config',
    sa.Column('server', sa.BigInteger(), nullable=False),
    sa.Column('starboard', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('server'),
    sa.UniqueConstraint('server')
    )
    op.create_table('stars',
    sa.Column('card', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('server', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server'], ['server_config.server'], ),
    sa.PrimaryKeyConstraint('card'),
    sa.UniqueConstraint('card'),
    sa.UniqueConstraint('message')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars')
    op.drop_table('server_config')
    # ### end Alembic commands ###
